name: CrossWikiEditor-Mac-latest

on:
    push:
        branches: [ "master" ]

jobs:
    
    build:
        
        runs-on: macos-13  # For a list of available runner types, refer to
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        
        env:
            Solution_Name: CrossWikiEditor.sln
            Project_Directory: CrossWikiEditor
            Project_Path: CrossWikiEditor/CrossWikiEditor.csproj
            Publish_Profile_M1_Path: CrossWikiEditor/Properties/PublishProfiles/MacArm.pubxml
            Publish_Profile_Intel_Path: CrossWikiEditor/Properties/PublishProfiles/MacIntel.pubxml
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            
            # Install the .NET Core workload
            - name: Install .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x
                  dotnet-quality: 'preview'

            - name: Publish M1 version
              run: dotnet publish ${{ env.Project_Path }} -p:PublishProfile=${{ env.Publish_Profile_M1_Path }}
            
            - name: Publish Intel version
              run: dotnet publish ${{ env.Project_Path }} -p:PublishProfile=${{ env.Publish_Profile_Intel_Path }}
            
            # Upload the app: https://github.com/marketplace/actions/upload-a-build-artifact
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: Mac M1
                  path: ${{ env.Project_Directory }}/bin/publish/mac-arm/CrossWikiEditor
                  
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: Mac Intel
                  path: ${{ env.Project_Directory }}/bin/publish/mac-intel/CrossWikiEditor

            - name: Upload Artifacts TO Google Drive
              uses: ashotjanibekyan/Upload_Github_Artifacts_TO_GDrive@master
              with:
                  target: ${{ env.Project_Directory }}/bin/publish/mac-arm/CrossWikiEditor
                  credentials: ${{ secrets.GOOGLEDRIVEUPLOAD }}
                  parent_folder_id: '1c4CnqaQQFjeTcd6ydpBPLAsVQ-YgPNYa'
                  name: 'CrossWikiEditor-MacM1'
                  override: true

            - name: Upload Artifacts TO Google Drive
              uses: ashotjanibekyan/Upload_Github_Artifacts_TO_GDrive@master
              with:
                  target: ${{ env.Project_Directory }}/bin/publish/mac-intel/CrossWikiEditor
                  credentials: ${{ secrets.GOOGLEDRIVEUPLOAD }}
                  parent_folder_id: '1c4CnqaQQFjeTcd6ydpBPLAsVQ-YgPNYa'
                  name: 'CrossWikiEditor-MacIntel'
                  override: true